POST http://www.localhost:3500/register
content-type: application/json

{
    "user": "ayesha",
    "pwd": "156"
}
###
POST http://www.localhost:3500/auth
content-type: application/json

{
    "user": "ayesha",
    "pwd": "156"
}

###
GET http://www.localhost:3500/refresh
content-type: application/json

{
    "user": "ammar",
    "pwd": "156"
}

###
GET http://www.localhost:3500/logout
content-type: application/json

{
    "user": "ammar",
    "pwd": "156"
}

###

PUT http://www.localhost:3500/contacts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVc2VySW5mbyI6eyJ1c2VybmFtZSI6ImF5ZXNoYSJ9LCJpYXQiOjE2ODE4MDkwMjksImV4cCI6MTY4MTgwOTkyOX0.B1vH6jYWbiqTz57mfzP8CSx1mLsOX8E5cKaEcrf8Vug
content-type: application/json

{
    "contact":"tom"
}

###
GET http://www.localhost:3500/contacts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVc2VySW5mbyI6eyJ1c2VybmFtZSI6ImFtbWFyIn0sImlhdCI6MTY4MTgwNTQ2OSwiZXhwIjoxNjgxODA2MzY5fQ.QYUdyI9l7zfi-2CKrRM2dzEzU6USpE0NyWJ2wxc0VzU

###
GET http://www.localhost:3500/chats/ammar
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVc2VySW5mbyI6eyJ1c2VybmFtZSI6ImF5ZXNoYSJ9LCJpYXQiOjE2ODE4MTI2ODMsImV4cCI6MTY4MTgxMzU4M30.YazzRYP4u_FCIQzBb3pJ0lkkS-Gx4rC2u3h5v5DlNww
